import test,{before,after,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {JSDOM} from 'jsdom';
import {cigaretteGroups,packPieces,PK_PRICES} from '../src/cigaretteMetrics.js';
import {renderCigarettes} from '../src/cigarettes.js';
let db;const admin='00000000-0000-0000-0000-000000000001',staff='00000000-0000-0000-0000-000000000002';
const migration=await fs.readFile(new URL('../supabase/migrations/20261006163828_cigarettes_b145.sql',import.meta.url),'utf8');
const packMigration=await fs.readFile(new URL('../supabase/migrations/20261008164423_cigarette_packs_b147.sql',import.meta.url),'utf8');
const actor=id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
const packSales=(packs=0,price=260)=>PK_PRICES.map(p=>({price:p,packs:p===price?packs:0,amount:p===price?packs*p:0}));
const call=(action,payload={},outlet=1,date='2026-10-06')=>db.query('select public.save_cigarette_action($1,$2,$3,$4) result',[outlet,date,action,JSON.stringify({...action==='sales'?{pack_entries:packSales()}:action==='add'?{pack_price:0}:{},...payload})]);
const work=async(outlet=1,date='2026-10-06')=>(await db.query('select public.get_cigarette_workspace($1,$2) result',[outlet,date])).rows[0].result;
const reject=async(fn,pattern)=>{await db.exec('savepoint expected_failure');try{await assert.rejects(fn(),pattern);}finally{await db.exec('rollback to expected_failure;release savepoint expected_failure');}};
const sales=(pieces=5)=>[10,15,20,25,28,30].map(price=>({price,pieces:price===10?pieces:0,amount:price===10?pieces*10:0}));
before(async()=>{
 db=new PGlite();await db.exec(await fs.readFile(new URL('fixtures/payroll-schema.sql',import.meta.url),'utf8'));
 await db.exec(`create function private.has_photo_checkin(uuid) returns boolean language sql as $$select true$$;
 create table categories(id integer primary key,name text);create table vendors(id integer primary key,name text,purchase_enabled boolean default true);
 create table items(id varchar primary key,name text,category_id integer,vendor_id integer,unit text,pack_size text,minimum_stock numeric default 0,reorder_qty numeric default 0,active boolean default true,purchase_enabled boolean default true,created_at timestamptz default now());
 create table cigarette_profiles(item_id varchar primary key references items(id),pieces_per_pack integer,active boolean default true);
 create table outlet_items(outlet_id integer,item_id varchar,active boolean default true,stock_unit text,count_cycle text default 'CONTROLLED',order_strategy text default 'CONTROLLED',preferred_vendor_id integer,target_stock numeric,minimum_stock numeric,order_rounding numeric,count_weekday integer,unique(outlet_id,item_id));
 create table purchases(id varchar primary key,business_date date,outlet_id integer,user_id uuid,vendor_id integer,vendor_name text,item_id varchar,qty numeric,unit text,purchase_unit text,base_qty numeric,invoice_amount numeric,entry_type text,receipt_status text,created_at timestamptz default now());
 create table stock_locations(id bigint primary key,outlet_id integer,is_default boolean);
 create table stocktakes(id bigint generated by default as identity primary key,outlet_id integer,location_id bigint,business_date date,stocktake_type text,status text,started_by uuid,submitted_by uuid,submitted_at timestamptz);
 create table stocktake_lines(id bigint generated by default as identity primary key,stocktake_id bigint,item_id text,counted_quantity_base numeric,display_quantity numeric,display_unit text,note text);
 create table inventory_entries(item_id text,outlet_id integer,count_now numeric,business_date date,created_at timestamptz);
 create function private.purchase_name_allowed(text,text) returns boolean language sql as $$select true$$;
 insert into outlets(id,name) values(1,'Teapot'),(2,'ChaiCafe');insert into vendors values(1,'Kini'),(2,'ITC'),(3,'Advance');insert into categories values(1,'Cigarettes');
 insert into items(id,name,category_id,vendor_id,unit,pack_size) values('a','Kings',1,2,'Pc','10'),('b','Advance',1,3,'Pc','20');
 insert into cigarette_profiles values('a',10,true),('b',20,true);
 insert into outlet_items(outlet_id,item_id,preferred_vendor_id) values(1,'a',2),(1,'b',3),(2,'a',2),(2,'b',3);
 insert into stock_locations values(1,1,true),(2,2,true);
 insert into users(id,auth_user_id,name,role,access_class,outlet_id) values('${admin}','${admin}','Owner','Owner','ADMIN',null),('${staff}','${staff}','Staff','Staff','STAFF',1);
 `);
 const guards=await fs.readFile(new URL('../supabase/stock_function_guards_b109.sql',import.meta.url),'utf8');
 const start=guards.indexOf('CREATE OR REPLACE FUNCTION public.get_tonights_stock');const end=guards.indexOf('$function$;',start)+12;
 await db.exec(guards.slice(start,end));await db.exec(migration);await db.exec(packMigration);await db.exec(await fs.readFile(new URL('../supabase/migrations/20261009175425_cigarette_order_authority_b148.sql',import.meta.url),'utf8'));await db.exec(await fs.readFile(new URL('../supabase/migrations/20261009183320_cigarette_pk450_b149.sql',import.meta.url),'utf8'));await db.exec(await fs.readFile(new URL('../supabase/migrations/20261009183745_cigarette_order_pack_size_b150.sql',import.meta.url),'utf8'));await db.exec(await fs.readFile(new URL('../supabase/migrations/20261009190924_cigarette_purchase_pack_size_b151.sql',import.meta.url),'utf8'));
});
after(()=>db?.close());beforeEach(async()=>{await db.exec('begin');await actor(admin);});afterEach(()=>db.exec('rollback;reset role'));
test('Teapot uses only Kini; Chai has separate ITC and Advance brand cards',async()=>{
 const t=await work(),c=await work(2);assert.deepEqual(t.vendors.map(v=>v.name),['Kini']);assert.ok(t.items.every(i=>i.vendor_name==='Kini'));
 assert.deepEqual(c.vendors.map(v=>v.name),['Advance','ITC']);assert.equal(c.items.find(i=>i.item_id==='a').vendor_name,'ITC');
});
test('saved order remains available after more than thirty later daily actions',async()=>{
 await call('order',{vendor_id:1,request_id:crypto.randomUUID(),entries:[{item_id:'a',packs:5,pack_price:null}]});
 await db.exec(`insert into public.cigarette_audit(outlet_id,business_date,action,actor_id,payload) select 1,'2026-10-06','settings','${admin}','{"input":{}}'::jsonb from generate_series(1,35)`);
 assert.equal((await work()).audit.filter(a=>a.action==='order').length,1);
});
test('order pack sizes persist for later orders without changing stock conversion; new brands need no order PK',async()=>{
 await call('order',{vendor_id:1,request_id:crypto.randomUUID(),entries:[{item_id:'a',packs:5,pieces_per_pack:20}]});
 const item=(await work(1,'2026-10-07')).items.find(i=>i.item_id==='a');assert.equal(item.order_pack_size,20);assert.equal(item.pieces_per_pack,10);
 assert.equal((await work(2)).items.find(i=>i.item_id==='a').order_pack_size,10);
 for(const size of [0,1.5,101,null])await reject(()=>call('order',{vendor_id:1,request_id:crypto.randomUUID(),entries:[{item_id:'a',packs:1,pieces_per_pack:size}]}),/pieces per pack/);
 await call('add',{name:'Goldflake small',pack:10,pack_price:null,source:'orders',vendor_id:1});
 assert.ok((await work(1,'2026-10-07')).items.some(i=>i.item_name==='Goldflake small'));
});
test('purchase requires SK and whole packs; canonical quantity and vendor feed existing credits; retry cannot duplicate',async()=>{
 await actor(staff);const p={vendor_id:1,request_id:crypto.randomUUID(),entries:[{item_id:'a',packs:2,amount:180,pos_price:10,pack_price:260}]};
 await call('purchase',p);await call('purchase',p);
 const rows=(await db.query('select * from purchases')).rows;assert.equal(rows.length,1);assert.equal(Number(rows[0].base_qty),20);assert.equal(rows[0].unit,'Pack');assert.equal(rows[0].vendor_name,'Kini');
 const w=await work();assert.equal(w.items.find(i=>i.item_id==='a').purchased,20);assert.equal(w.items.find(i=>i.item_id==='a').pos_price,10);
 await reject(()=>call('purchase',{...p,request_id:crypto.randomUUID(),entries:[{item_id:'b',packs:1,amount:100}]}),/Set the SK/);
 assert.equal((await db.query('select count(*) n from purchases')).rows[0].n,1);
 await reject(()=>call('purchase',{...p,vendor_id:2,request_id:crypto.randomUUID()}),/Wrong cigarette vendor/);
 await reject(()=>call('purchase',{...p,request_id:crypto.randomUUID(),entries:[{...p.entries[0],packs:1.5}]}),/whole packs/);
});
test('purchase uses entered pack size, preserves earlier receipts and defaults independently per café',async()=>{
 const buy=async(size,packs,amount,date)=>call('purchase',{vendor_id:1,request_id:crypto.randomUUID(),entries:[{item_id:'a',packs,amount,pos_price:10,pack_price:260,pieces_per_pack:size}]},1,date);
 await buy(10,2,160,'2026-10-06');await buy(20,3,480,'2026-10-07');
 const old=(await work(1,'2026-10-06')).items.find(i=>i.item_id==='a'),now=(await work(1,'2026-10-07')).items.find(i=>i.item_id==='a');
 assert.equal(old.purchased,20);assert.equal(now.purchased,60);assert.equal(now.pieces_per_pack,20);assert.equal(now.cost_per_piece,8);assert.equal((await work(2)).items.find(i=>i.item_id==='a').pieces_per_pack,10);
 assert.equal((await work(1,'2026-10-07')).purchases[0].pieces_per_pack,20);
 for(const size of [0,1.5,101,null])await reject(()=>buy(size,1,80,'2026-10-07'),/pieces per pack/);
});
test('SK assignment is café-specific; historical close snapshots retain their mapping',async()=>{
 await call('settings',{item_id:'a',pos_price:10});assert.equal((await work()).items.find(i=>i.item_id==='a').pos_price,10);assert.equal((await work(2)).items.find(i=>i.item_id==='a').pos_price,null);
 await call('sales',{entries:sales()});await call('close',{entries:[{item_id:'a',pieces:10},{item_id:'b',pieces:0}]});await call('settings',{item_id:'a',pos_price:15});assert.equal((await work()).day.report.brands.find(i=>i.item_id==='a').pos_price,10);
});
test('daily POS sales require all groups; close requires all brands; closed movements need owner reopening',async()=>{
 await reject(()=>call('sales',{entries:sales().slice(0,2)}),/every SK group/);
 await reject(()=>call('close',{entries:[{item_id:'a',pieces:10},{item_id:'b',pieces:0}]}),/Save SK and PK POS sales/);
 await call('sales',{entries:sales()});await reject(()=>call('close',{entries:[{item_id:'a',pieces:10}]}),/every cigarette brand/);
 await call('close',{entries:[{item_id:'a',pieces:10},{item_id:'b',pieces:0}]});assert.ok((await work()).day.closed_at);
 await reject(()=>call('sales',{entries:sales(6)}),/Day is closed/);
 await actor(staff);await reject(()=>call('reopen',{reason:'Correction'}),/Owner access/);
 await actor(admin);await call('reopen',{reason:'Correct count'});await call('sales',{entries:sales(6)});assert.equal((await work()).day.sales[0].pieces,6);
});
test('transfers leave source on dispatch and enter destination only on confirmation; repeat receipt fails',async()=>{
 await call('dispatch',{item_id:'a',destination:2,pieces:10});const t=(await work(2)).transfers[0];assert.equal((await work()).items.find(i=>i.item_id==='a').transfer_out,10);assert.equal((await work(2)).items.find(i=>i.item_id==='a').transfer_in,0);
 await call('receive',{transfer_id:t.id},2);assert.equal((await work(2)).items.find(i=>i.item_id==='a').transfer_in,10);await reject(()=>call('receive',{transfer_id:t.id},2),/already received/);
});
test('cigarette permission, café boundaries, direct-write and adjustment approval are enforced',async()=>{
 await actor(staff);await reject(()=>work(2),/Outlet access/);await reject(()=>call('adjust',{item_id:'a',pieces:-2,reason:'Damaged'}),/approval required/);
 await db.query("update users set permissions=$1 where id=$2",[JSON.stringify({module_access:{cigarettes:false}}),staff]);await reject(()=>work(),/disabled/);
 await db.exec('set local role authenticated');await reject(()=>db.query("update cigarette_days set sales='[]'"),/permission denied/);await db.exec('reset role');
 await actor(admin);await call('adjust',{item_id:'a',pieces:-2,reason:'Damaged'});assert.equal((await work()).items.find(i=>i.item_id==='a').adjustment,-2);
 await db.exec('set local role anon');await reject(()=>work(),/permission denied/);
});
test('new brands use same identity across cafés; reused brand cannot change pack size',async()=>{
 await call('add',{name:'New brand',pack:10,vendor_id:1});let id=(await work()).items.find(i=>i.item_name==='New brand').item_id;
 await call('add',{name:'new BRAND',pack:10,vendor_id:3},2);assert.equal((await work(2)).items.find(i=>i.item_name==='New brand').item_id,id);
 await reject(()=>call('add',{name:'New brand',pack:20,vendor_id:1}),/different pack size/);
});
test('SK reconciliation measures group movement without inventing brand sales; gaps and unmapped brands stay incomplete',()=>{
 const items=[{item_id:'a',pos_price:10,opening:50,opening_date:'2026-10-05',purchased:20,transfer_in:0,transfer_out:10,adjustment:-2,cost_per_piece:8},{item_id:'b',pos_price:10,opening:40,opening_date:'2026-10-05',purchased:0,transfer_in:0,transfer_out:0,adjustment:0,cost_per_piece:7}];
 const g=cigaretteGroups(items,sales(30),{a:30,b:35},'2026-10-06')[0];assert.equal(g.movement,33);assert.equal(g.difference,3);assert.equal(g.cost,259);assert.equal(packPieces(2,3,20),43);
 assert.equal(cigaretteGroups([...items,{item_id:'c',pos_price:null}],sales(30),{a:30,b:35},'2026-10-06')[0].difference,null);
 assert.equal(cigaretteGroups(items,sales(30),{a:30,b:35},'2026-10-07')[0].difference,null);
});
test('purchase UI demands SK beside every brand; sales UI uses SK groups; blank counts are not preconfirmed',async()=>{
 const dom=new JSDOM('<main></main>'),view=dom.window.document.querySelector('main'),calls=[];
 const data={vendors:[{id:1,name:'Kini'}],items:[{item_id:'a',item_name:'Kings',vendor_id:1,pieces_per_pack:10,pos_price:null,opening:0}],purchases:[],audit:[],history:[],transfers:[],outlets:[{id:1,name:'Teapot'},{id:2,name:'ChaiCafe'}],day:null};
 const client={rpc:async(name,args)=>{calls.push({name,args});if(name==='get_effective_business_day')return{data:'2026-10-06'};if(name==='get_cigarette_workspace')return{data};return{data:{saved:true}};}};
 const profile={access_class:'ADMIN',context_outlet_id:1,_cigaretteTab:'purchase'};await renderCigarettes(view,client,profile);assert.equal(view.querySelectorAll('details[open]').length,0);assert.equal(view.querySelector('.cig-sk').required,true);
 const r=view.querySelector('.cig-entry-row');r.querySelector('.cig-include').checked=true;r.querySelector('.cig-packs').value=2;r.querySelector('.cig-amount').value=180;await view.querySelector('.cig-save').onclick();assert.equal(calls.some(c=>c.name==='save_cigarette_action'),false);
 r.querySelector('.cig-sk').value='10';await view.querySelector('.cig-save').onclick();assert.equal(calls.some(c=>c.name==='save_cigarette_action'),false);
 assert.equal(r.querySelector('.cig-pk').required,true);assert.equal(r.querySelector('.cig-pack-size').value,'10');r.querySelector('.cig-pack-size').value='20';r.querySelector('.cig-pk').value='260';await view.querySelector('.cig-save').onclick();assert.equal(calls.find(c=>c.name==='save_cigarette_action').args.p_payload.entries[0].pos_price,10);assert.equal(calls.find(c=>c.name==='save_cigarette_action').args.p_payload.entries[0].pack_price,260);assert.equal(calls.find(c=>c.name==='save_cigarette_action').args.p_payload.entries[0].pieces_per_pack,20);
 view.querySelector('[data-cig-tab="sales"]').click();assert.equal(view.querySelectorAll('.cig-sales-row').length,10);assert.match(view.textContent,/SK10/);assert.match(view.textContent,/PK400/);assert.equal(view.querySelectorAll('.cig-sold')[0].value,'');
 view.querySelector('[data-cig-tab="stock"]').click();assert.equal(view.querySelector('.cig-count-packs').value,'');assert.equal(view.querySelector('#cigVerified').checked,false);dom.window.close();
});

test('general catalogue and old count endpoints cannot bypass cigarette monitoring',async()=>{
 const c=(await db.query("select private.vendor_catalogue(1,'purchase') result")).rows[0].result;assert.equal(c.items.length,0);assert.deepEqual(c.cigarette_item_ids.sort(),['a','b']);
 for(const fn of ['save_tonights_stocktake','save_monthly_stocktake'])await reject(()=>db.query('select public.'+fn+'(1,$1,$2,$3)',['2026-10-06',admin,JSON.stringify([{item_id:'a',count_now:10,unit:'Pc'}])]),/Cigarettes module/);
 await reject(()=>call('receive',{transfer_id:crypto.randomUUID()},2,'2026-10-05'),/unavailable/);
});

test('PK mapping is café-specific, preserves SK, and freezes with audited close and summary totals',async()=>{
 await call('settings',{item_id:'a',pos_price:10,pack_price:260});await call('settings',{item_id:'b',pos_price:15,pack_price:0});
 await call('settings',{item_id:'a',pack_price:450});let w=await work();assert.equal(w.items.find(i=>i.item_id==='a').pos_price,10);assert.equal(w.items.find(i=>i.item_id==='a').pack_price,450);assert.equal((await work(2)).items.find(i=>i.item_id==='a').pack_price,null);
 await call('sales',{entries:sales(5),pack_entries:packSales(2,450)});await call('close',{entries:[{item_id:'a',pieces:10},{item_id:'b',pieces:0}]});
 await call('settings',{item_id:'a',pack_price:400});w=await work();assert.equal(w.day.report.brands.find(i=>i.item_id==='a').pack_price,450);assert.equal(w.day.report.pack_sales.find(p=>p.price===450).packs,2);
 const summary=(await db.query("select public.get_cigarette_summary(1,'2026-10-06') result")).rows[0].result;assert.equal([...summary.sales,...summary.pack_sales].reduce((n,s)=>n+s.amount,0),950);
 assert.ok(w.audit.some(a=>a.action==='sales'&&a.payload.input.pack_entries.find(p=>p.price===450).packs===2));
 await reject(()=>call('settings',{item_id:'a',pack_price:999}),/PK140/);
});
test('PK POS entries require all four codes and whole nonnegative packs; closed-day protections apply',async()=>{
 await reject(()=>call('settings',{item_id:'a',pack_price:350}),/PK450/);
 await reject(()=>call('sales',{entries:sales(),pack_entries:packSales().map(p=>p.price===450?{...p,price:350}:p)}),/Invalid PK sale/);
 await reject(()=>call('sales',{entries:sales(),pack_entries:null}),/every PK/);
 await reject(()=>call('sales',{entries:sales(),pack_entries:packSales().slice(0,3)}),/every PK/);
 await reject(()=>call('sales',{entries:sales(),pack_entries:[...packSales().slice(0,3),packSales()[0]]}),/Duplicate PK/);
 for(const packs of [-1,1.5])await reject(()=>call('sales',{entries:sales(),pack_entries:packSales(packs)}),/whole packs/);
 await reject(()=>call('sales',{entries:sales(),pack_entries:packSales().map((p,i)=>i===0?{...p,price:999}:p)}),/Invalid PK/);
 assert.equal((await work()).day,null);await call('sales',{entries:sales(),pack_entries:packSales(2)});
 await call('close',{entries:[{item_id:'a',pieces:10},{item_id:'b',pieces:0}]});await reject(()=>call('sales',{entries:sales(),pack_entries:packSales(3)}),/Day is closed/);
 await call('reopen',{reason:'Correct pack sales'});await call('sales',{entries:sales(),pack_entries:packSales(3)});assert.equal((await work()).day.pack_sales.find(p=>p.price===260).packs,3);
});
test('purchase and add require explicit PK or No pack sales; orders also remember PK',async()=>{
 const entry={item_id:'a',packs:1,amount:100,pos_price:10};const p={vendor_id:1,request_id:crypto.randomUUID(),entries:[entry]};
 await reject(()=>call('purchase',p),/Set the PK/);assert.equal((await db.query('select count(*) n from purchases')).rows[0].n,0);
 await call('purchase',{...p,entries:[{...entry,pack_price:0}]});assert.equal((await work()).items.find(i=>i.item_id==='a').pack_price,0);
 await call('order',{vendor_id:1,request_id:crypto.randomUUID(),entries:[{item_id:'a',packs:1,pack_price:260}]});assert.equal((await work()).items.find(i=>i.item_id==='a').pack_price,260);
 await reject(()=>call('add',{name:'Missing PK',pack:10,vendor_id:1,pack_price:null}),/Set the PK/);
 await call('add',{name:'New PK brand',pack:10,vendor_id:1,pack_price:140});assert.equal((await work()).items.find(i=>i.item_name==='New PK brand').pack_price,140);
});
test('pack reconciliation converts packs to pieces without allocating brand sales or double-counting connected groups',()=>{
 const items=[{item_id:'a',pos_price:10,pack_price:260,pieces_per_pack:10,opening:50,opening_date:'2026-10-05',cost_per_piece:8},{item_id:'b',pos_price:15,pack_price:260,pieces_per_pack:10,opening:30,opening_date:'2026-10-05',cost_per_piece:9}];
 const groups=cigaretteGroups(items,sales(5),{a:30,b:20},'2026-10-06',packSales(2));const g=groups.find(g=>g.brands.length);
 assert.equal(g.label,'SK10 / SK15 / PK260');assert.equal(g.sold,25);assert.equal(g.movement,30);assert.equal(g.difference,5);assert.equal(g.cost,250);assert.equal(g.exposure,null);
 assert.equal(groups.reduce((n,g)=>n+g.brands.length,0),2);assert.equal(groups.reduce((n,g)=>n+(g.movement||0),0),30);
 const single=cigaretteGroups([items[0]],sales(5),{a:20},'2026-10-06',packSales(2)).find(g=>g.brands.length);assert.equal(single.difference,5);assert.equal(single.exposure,50);
 const looseOnly=cigaretteGroups(items,sales(5),{a:45,b:30},'2026-10-06',packSales());assert.equal(looseOnly.find(g=>g.label==='SK10').difference,0);assert.equal(looseOnly.find(g=>g.label==='SK15').difference,0);assert.equal(looseOnly.reduce((n,g)=>n+g.brands.length,0),2);
});
test('mixed pack sizes, missing PK mapping and missing counts cannot produce a false match',()=>{
 const a={item_id:'a',pos_price:10,pack_price:260,pieces_per_pack:10,opening:50,opening_date:'2026-10-05'};
 const b={...a,item_id:'b',pieces_per_pack:20};
 let g=cigaretteGroups([a,b],sales(5),{a:20,b:20},'2026-10-06',packSales(2)).find(g=>g.brands.length);assert.equal(g.difference,null);assert.equal(g.reason,'Mixed pack sizes');
 g=cigaretteGroups([a,{...b,pack_price:null}],sales(),{a:20,b:20},'2026-10-06',packSales(2)).find(g=>g.brands.length);assert.equal(g.complete,false);
 g=cigaretteGroups([a],sales(),{},'2026-10-06',packSales(2)).find(g=>g.brands.length);assert.equal(g.complete,false);
 const zero=cigaretteGroups([{...a,pack_price:null}],sales(5),{a:45},'2026-10-06',packSales()).find(g=>g.brands.length);assert.equal(zero.difference,0);
});
test('PK sales UI calculates amounts, preserves drafts, saves packs separately and excludes them from SK entries',async()=>{
 const dom=new JSDOM('<main></main>',{url:'https://example.test'}),view=dom.window.document.querySelector('main'),calls=[];
 const data={vendors:[{id:1,name:'Kini'}],items:[{item_id:'a',item_name:'Brand',vendor_id:1,pieces_per_pack:10,pos_price:140,pack_price:260}],purchases:[],audit:[],history:[],transfers:[],outlets:[],day:null};
 const client={rpc:async(name,args)=>{calls.push({name,args});return {data:name==='get_effective_business_day'?'2026-10-06':name==='get_cigarette_workspace'?data:{saved:true}};}};
 const profile={access_class:'ADMIN',context_outlet_id:1,_cigaretteTab:'sales'};await renderCigarettes(view,client,profile);
 view.querySelector('#cigZero').click();const row=view.querySelector('[data-sale-code="PK260"]');row.querySelector('.cig-sold').value='2';row.querySelector('.cig-sold').dispatchEvent(new dom.window.Event('input',{bubbles:true}));assert.equal(row.querySelector('.cig-revenue').value,'520.00');
 row.querySelector('.cig-revenue').value='510';row.querySelector('.cig-revenue').dispatchEvent(new dom.window.Event('input',{bubbles:true}));
 view.querySelector('[data-cig-tab="purchase"]').click();view.querySelector('[data-cig-tab="sales"]').click();assert.equal(view.querySelector('[data-sale-code="PK260"] .cig-sold').value,'2');assert.equal(view.querySelector('[data-sale-code="PK260"] .cig-revenue').value,'510');assert.equal(view.querySelector('[data-sale-code="SK140"] .cig-sold').value,'0');
 await view.querySelector('#cigSales').onsubmit({preventDefault(){}});const input=calls.find(c=>c.name==='save_cigarette_action').args.p_payload;assert.equal(input.entries.length,7);assert.equal(input.pack_entries.length,4);assert.deepEqual(input.pack_entries.find(p=>p.price===260),{price:260,packs:2,amount:510});assert.ok(input.entries.every(p=>'pieces' in p&&!('packs' in p)));dom.window.close();
});
