import test,{before,after,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import {PGlite} from '@electric-sql/pglite';
import {JSDOM} from 'jsdom';
import {bindItemAdder} from '../src/vendorCatalogue.js';
import {renderVendorPurchases} from '../src/vendorPurchases.js';
const migration=await fs.readFile(new URL('../supabase/migrations/20261006160301_vendor_catalogue_b143.sql',import.meta.url),'utf8');
const owner='00000000-0000-0000-0000-000000000001',staff='00000000-0000-0000-0000-000000000002';let db;
const actor=id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
const add=(name='New item',module='purchase',outlet=1,unit='kg',category=1,categoryName=null)=>db.query('select public.add_vendor_catalogue_item($1,$2,1,$3,$4,$5,$6) item',[outlet,module,name,category,categoryName,unit]);
const catalogue=async(module='purchase',outlet=1)=>(await db.query('select public.get_vendor_catalogue($1,$2) data',[outlet,module])).rows[0].data;
const reject=async(fn,pattern)=>{await db.exec('savepoint expected_failure');try{await assert.rejects(fn(),pattern);}finally{await db.exec('rollback to expected_failure;release savepoint expected_failure');}};
before(async()=>{
 db=new PGlite();await db.exec(await fs.readFile(new URL('fixtures/payroll-schema.sql',import.meta.url),'utf8'));
 await db.exec(`create table categories(id integer generated by default as identity primary key,name varchar(100) unique not null);
 create table vendors(id integer primary key,name text);
 create table items(id varchar(50) primary key,name varchar(150) not null,category_id integer references categories(id),vendor_id integer references vendors(id),unit varchar(30) not null,active boolean default true,created_at timestamptz default now());
 create table outlet_items(id bigint generated by default as identity primary key,outlet_id integer references outlets(id),item_id varchar references items(id),active boolean default true,stock_unit text,count_cycle text default 'MONTHLY',order_strategy text default 'MANUAL',preferred_vendor_id integer references vendors(id),unique(outlet_id,item_id));
 create table item_units(id bigint generated by default as identity primary key,item_id varchar references items(id),unit_name text,base_multiplier numeric,is_purchase_unit boolean,is_count_unit boolean,active boolean,unique(item_id,unit_name));
 create table purchases(id varchar primary key,business_date date,outlet_id integer,user_id uuid,vendor_id integer,vendor_name text,item_id varchar,qty numeric,unit varchar,invoice_amount numeric,entry_type varchar,created_at timestamptz default now());
 insert into outlets(id,name) values(1,'Teapot'),(2,'Chai');insert into vendors values(1,'Supplier'),(2,'Empty vendor');insert into categories(name) values('Food');
 insert into users(id,auth_user_id,name,access_class,outlet_id) values('${owner}','${owner}','Owner','ADMIN',null),('${staff}','${staff}','Staff','STAFF',1);
 `);
 await db.exec(migration);
});
after(async()=>db?.close());beforeEach(async()=>{await db.exec('begin');await actor(staff);});afterEach(async()=>db.exec('rollback;reset role'));
test('staff additions share catalogue in both domains, normalize/reuse duplicates and preserve units',async()=>{
 const a=(await add('  Mushroom   mix ')).rows[0].item;
 assert.equal(a.item_name,'Mushroom mix');assert.equal((await catalogue('orders')).items[0].item_id,a.item_id);
 assert.equal((await add('mushroom MIX')).rows[0].item.item_id,a.item_id);
 assert.equal((await db.query('select count(*) n from items')).rows[0].n,1);
 assert.equal((await db.query('select count(*) n from item_units')).rows[0].n,1);
 await reject(()=>add('Mushroom mix','orders',1,'Pack'),/existing item/);
 assert.equal((await catalogue()).vendors.length,2);
});
test('new categories are reused and existing global item attaches only to the requested café',async()=>{
 const a=(await add('Juice','orders',1,'L',null,' Fresh   juices ')).rows[0].item;
 await actor(owner);assert.equal((await add('juice','purchase',2,'L',null,'FRESH JUICES')).rows[0].item.item_id,a.item_id);
 assert.equal((await catalogue('orders',2)).items[0].item_id,a.item_id);
 assert.equal((await db.query('select count(*) n from categories')).rows[0].n,2);
 await add('Second juice','orders',2,'L',null,'fresh juices');assert.equal((await db.query('select count(*) n from categories')).rows[0].n,2);
});
test('authentication, module toggles and café boundaries are enforced for read and create',async()=>{
 await reject(()=>add('Wrong café','purchase',2),/Outlet access/);
 await reject(()=>catalogue('purchase',2),/Outlet access/);
 await db.query("update users set permissions='{"+'"module_access":{"purchase":false,"orders":true}'+"}' where id=$1",[staff]);
 await reject(()=>add(),/disabled/);await reject(()=>catalogue(),/disabled/);await add('Order only','orders');
 await actor('');await reject(()=>add(),/Authenticated/);await actor(owner);await reject(()=>add('Invalid module','summary'),/operational module/);
 await db.exec('set role anon');await reject(()=>catalogue(),/permission denied/);
});
test('authenticated wrapper permits creation but no direct catalogue editing; inactive items remain protected',async()=>{
 await db.exec('set role authenticated');await add();await reject(()=>db.query("update items set name='Changed'"),/permission denied/);await db.exec('reset role');
 await db.query('update items set active=false');await reject(()=>add(),/inactive/);
 await reject(()=>add('Bad','purchase',1,''),/name and unit/);
 await reject(()=>add('Bad category','purchase',1,'kg',null,''),/category/);
});
test('purchase saves canonical vendor, last price and all lines atomically; orders cannot see invoice prices',async()=>{
 const a=(await add()).rows[0].item;
 const entries=[{item_id:a.item_id,qty:2,unit:'kg',invoice_amount:100,entry_type:'item'}];
 const save=p=>db.query("select public.save_purchase_entries(1,date '2026-10-06',$1,'Supplier',$2) n",[staff,JSON.stringify(p)]);
 assert.equal((await save(entries)).rows[0].n,1);assert.equal((await catalogue()).items[0].last_price,50);assert.equal((await catalogue('orders')).items[0].last_price,null);
 assert.equal((await db.query('select vendor_id from purchases')).rows[0].vendor_id,1);
 await reject(()=>save([...entries,{...entries[0],qty:0}]),/Check item/);assert.equal((await db.query('select count(*) n from purchases')).rows[0].n,1);
 await reject(()=>save([{...entries[0],unit:'Pack'}]),/Check item/);
 await reject(()=>save([{...entries[0],item_id:'unknown'}]),/Check item/);
});

const makeCatalogue=()=>({vendors:[{id:1,name:'Supplier'},{id:2,name:'Empty vendor'}],categories:[{id:1,name:'Food'}],items:[{item_id:'one',item_name:'Chicken',category_id:1,category_name:'Food',vendor_id:1,vendor_name:'Supplier',unit:'kg',order_unit:'kg',last_price:100},{item_id:'two',item_name:'Milk',category_id:1,category_name:'Food',vendor_id:2,vendor_name:'Empty vendor',unit:'L',order_unit:'L'}]});
function uiClient(cat,{saveError}={}){const calls=[];return {calls,from(){const q={select(){return q;},eq(){return q;},order(){return q;},limit(){return Promise.resolve({data:[]});}};return q;},rpc:async(name,args)=>{calls.push({name,args});if(name==='get_effective_business_day')return{data:'2026-10-06'};if(name==='get_vendor_catalogue')return{data:cat};if(name==='get_tomorrows_order')return{data:cat.items.map(i=>({...i,suggested_qty:1,current_stock:0,order_strategy:'DAILY_FORECAST'}))};if(name==='add_vendor_catalogue_item')return{data:{...cat.items[0],item_id:'new',item_name:args.p_name,category_id:args.p_category_id||9,category_name:args.p_category_name||'Food',unit:args.p_unit,order_unit:args.p_unit,vendor_id:args.p_vendor_id,vendor_name:cat.vendors.find(v=>v.id===args.p_vendor_id).name,last_price:null}};if(name==='save_purchase_entries')return saveError?{error:{message:saveError}}:{data:args.p_entries.length};return{data:[]};}};}
const input=(dom,el,value)=>{el.value=value;el.dispatchEvent(new dom.window.Event('input'));};
const tick=()=>new Promise(r=>setTimeout(r,0));
test('purchases use collapsed vendors, editable last price, independent vendor saves and retained failed drafts',async()=>{
 const dom=new JSDOM('<main></main>'),view=dom.window.document.querySelector('main'),cat=makeCatalogue(),client=uiClient(cat);
 await renderVendorPurchases(view,client,{id:staff},{outletId:1,businessDate:'2026-10-06',catalogue:cat});
 assert.equal(view.querySelectorAll('details[open]').length,0);const cards=view.querySelectorAll('.purchase-vendor-card');
 input(dom,cards[0].querySelector('.purchase-qty'),'2');assert.equal(cards[0].querySelector('.purchase-amount').value,'200.00');input(dom,cards[0].querySelector('.purchase-amount'),'180');
 input(dom,cards[1].querySelector('.purchase-qty'),'3');await cards[0].querySelector('.save-vendor-purchase').onclick();
 const save=client.calls.find(c=>c.name==='save_purchase_entries');assert.equal(save.args.p_vendor_name,'Supplier');assert.equal(save.args.p_entries[0].invoice_amount,180);assert.equal(cards[0].querySelector('.purchase-qty').value,'');assert.equal(cards[1].querySelector('.purchase-qty').value,'3');
 client.rpc=async()=>({error:{message:'Network failed'}});await cards[1].querySelector('.save-vendor-purchase').onclick();assert.equal(cards[1].querySelector('.purchase-qty').value,'3');assert.match(cards[1].textContent,/Network failed/);dom.window.close();
});
test('invoice total is vendor-specific and excludes hidden item quantities from save',async()=>{
 const dom=new JSDOM('<main></main>'),view=dom.window.document.querySelector('main'),cat=makeCatalogue(),client=uiClient(cat);await renderVendorPurchases(view,client,{id:staff},{outletId:1,businessDate:'2026-10-06',catalogue:cat});
 const card=view.querySelector('details');input(dom,card.querySelector('.purchase-qty'),'2');card.querySelector('[data-mode="invoice"]').click();input(dom,card.querySelector('.vendor-invoice'),'500');await card.querySelector('.save-vendor-purchase').onclick();
 assert.equal(client.calls[0].args.p_entries.length,1);assert.equal(client.calls[0].args.p_entries[0].entry_type,'invoice');assert.equal(client.calls[0].args.p_entries[0].invoice_amount,500);dom.window.close();
});
test('shared add form supports new categories/custom units, reuses existing items and keeps a failed form editable',async()=>{
 const dom=new JSDOM('<div></div>'),panel=dom.window.document.querySelector('div'),cat=makeCatalogue(),client=uiClient(cat);let added;
 bindItemAdder(panel,{client,outletId:1,module:'orders',vendor:cat.vendors[0],catalogue:cat,onAdded:async i=>{added=i;}});
 const f=panel.querySelector('form');f.elements.item_name.value='Special box';f.elements.category_id.value='new';f.elements.category_id.onchange();f.elements.category_name.value='Specials';f.elements.unit.value='other';f.elements.unit.onchange();f.elements.custom_unit.value='Carton';await f.onsubmit({preventDefault(){}});
 assert.equal(added.unit,'Carton');assert.equal(cat.categories.at(-1).name,'Specials');assert.equal(client.calls[0].args.p_module,'orders');assert.equal(cat.items.at(-1).item_name,'Special box');
 panel.hidden=false;bindItemAdder(panel,{client,outletId:1,module:'purchase',vendor:cat.vendors[0],catalogue:cat,onAdded:async i=>{added=i;}});input(dom,panel.querySelector('[name="item_name"]'),'Chicken');await panel.querySelector('.category-add-result').onclick();assert.equal(added.item_id,'one');assert.equal(client.calls.length,1);dom.window.close();
});
test('Orders creates an item in its vendor card while preserving another vendor quantity, and includes it in messages',async()=>{
 const dom=new JSDOM('<main></main>'),view=dom.window.document.querySelector('main'),cat=makeCatalogue(),client=uiClient(cat);
 const source=(await fs.readFile(new URL('../src/app.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace('export async function renderApp','async function renderApp').replaceAll('import.meta.env','({})');
 const context=vm.createContext({bindItemAdder,renderVendorPurchases,document:dom.window.document,CSS:{escape:s=>s},setTimeout,clearTimeout,console});vm.runInContext(source,context);
 await context.renderPurchases(view,client,{id:staff,access_class:'STAFF',outlet_id:1,outlets:{name:'Teapot'}},'orders');
 let cards=view.querySelectorAll('#tomorrowOrderRows details');input(dom,cards[1].querySelector('.order-qty'),'7');cards[0].querySelector('.order-card-add').click();
 const form=cards[0].querySelector('form');form.elements.item_name.value='New order item';form.elements.category_id.value='1';form.elements.unit.value='kg';await form.onsubmit({preventDefault(){}});
 cards=view.querySelectorAll('#tomorrowOrderRows details');assert.equal(cards[1].querySelector('.order-qty').value,'7');const added=view.querySelector('.order-suggestion-row[data-id="new"]');assert.ok(added);input(dom,added.querySelector('.order-qty'),'3');cards[0].querySelector('.category-message').click();assert.match(cards[0].querySelector('textarea').value,/New order item — 3 kg/);assert.equal(cat.items.at(-1).item_id,'new');dom.window.close();
});
