create schema private;create schema auth;create role anon;create role authenticated;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,private to authenticated;grant execute on function auth.uid() to authenticated;
create table public.attendance(id int4 generated by default as identity primary key,attendance_date date,outlet_id int4,staff_id int4,shift_start time,punch_time time,late_mins int4 default 0,half_day bool default false,status varchar default 'Present'::character varying,photo_url text,created_at timestamptz default now(),legacy_source_row int4);
create table public.daily_summaries(id varchar primary key,outlet_id int4,business_date date,saved_by uuid,saved_by_name varchar,role varchar,cash_sale numeric default 0,upi_sale numeric default 0,own_digital numeric default 0,discount numeric default 0,net_sale numeric default 0,swiggy_gross numeric default 0,swiggy_payout numeric default 0,zomato_gross numeric default 0,zomato_payout numeric default 0,opening_cash_system numeric default 0,opening_cash_actual numeric default 0,physical_cash numeric default 0,expected_cash numeric default 0,short_excess numeric default 0,summary_status varchar default 'OPEN'::character varying,is_closed bool default false,closed_by uuid,closed_at timestamptz,created_at timestamptz default now());
create table public.extra_time_dispatches(id int8 generated by default as identity primary key,request_id int8,prepared_by uuid,prep_qty numeric,prep_unit text,dispatched_qty numeric,dispatch_unit text default 'Pc'::text,dispatched_by uuid,dispatched_at timestamptz default now(),note text,received_qty numeric,received_by uuid,received_at timestamptz,receipt_note text);
create table public.extra_time_payments(id int8 generated by default as identity primary key,dispatch_id int8,staff_user_id uuid,category text,basis_qty numeric,basis_unit text,rate numeric,amount numeric,status text default 'PENDING_RATE'::text,created_at timestamptz default now(),salary_record_id varchar);
create table public.extra_time_requests(id int8 generated by default as identity primary key,request_group uuid default gen_random_uuid(),request_outlet_id int4,source_outlet_id int4,category text,item_name text,requested_qty numeric,unit text default 'Pc'::text,requested_by uuid,status text default 'REQUESTED'::text,requested_at timestamptz default now(),received_at timestamptz);
create table public.leave_requests(id int8 generated by default as identity primary key,staff_id int4,user_id uuid,outlet_id int4,leave_type varchar,start_date date,end_date date,reason text,attachment_path text,status varchar default 'PENDING'::character varying,requested_at timestamptz default now(),reviewed_by uuid,reviewed_at timestamptz,review_note text);
create table public.outlets(id int4 generated by default as identity primary key,name varchar,shift_start_hour int4 default 7,shift_start_minute int4 default 0,swiggy_payout_rate numeric default 0.7000,zomato_payout_rate numeric default 0.7000,created_at timestamptz default now(),timezone varchar default 'Asia/Kolkata'::character varying,default_open_time time,default_close_time time,theme_key text,theme_color text,attendance_absent_cutoff time default '22:00:00'::time without time zone,attendance_grace_minutes int4 default 15,manager_shift_offset_minutes int4 default 120,half_day_late_minutes int4 default 240);
create table public.salary_records(id varchar primary key,outlet_id int4,staff_id int4,period_start date,period_end date,basic_salary numeric,present_days numeric default 0,absent_days numeric default 0,absent_deduction numeric default 0,late_penalty numeric default 0,petty_advance numeric default 0,ot_credit numeric default 0,net_salary numeric,created_at timestamptz default now(),pay_date date,period_days int4,holiday_pay numeric default 0,holiday_days numeric default 0,late_mins int4 default 0,late_penalty_waived bool default false,loan_prev_balance numeric default 0,loan_deduct_this_month numeric default 0,loan_remaining numeric default 0,saved_by uuid,saved_by_name varchar,late_hours_edited numeric default 0,legacy_salary_id text,payroll_status text default 'FINALIZED'::text,payroll_details jsonb default '{}'::jsonb,payment_method text,payment_reference text,paid_at timestamptz);
create table public.staff(id int4 generated by default as identity primary key,name varchar,outlet_id int4,basic_salary numeric default 0,joining_date date,active bool default true,created_at timestamptz default now(),employment_end_date date,notes text,employment_status varchar default 'ACTIVE'::character varying,status_effective_from date,status_note text);
create table public.staff_advance_deductions(advance_id uuid,period_start date,amount numeric,salary_record_id varchar,posted_at timestamptz default now());
create table public.staff_advance_requests(id uuid default gen_random_uuid() primary key,staff_id int4,outlet_id int4,amount numeric,installments int4,note text default ''::text,status text default 'REQUESTED'::text,requested_by uuid,requested_at timestamptz default now(),decided_by uuid,decided_at timestamptz,decision_note text,paid_by uuid,paid_at timestamptz,business_date date,mode text,first_period date);
create table public.staff_payments(id int8 generated by default as identity primary key,business_date date,outlet_id int4,staff_id int4,staff_name varchar,payment_type varchar,amount numeric default 0,mode varchar default 'Cash'::character varying,created_by uuid,created_at timestamptz default now());
create table public.staff_shifts(id int8 generated by default as identity primary key,staff_id int4,outlet_id int4,shift_date date,start_time time,end_time time,shift_type varchar default 'REGULAR'::character varying,status varchar default 'SCHEDULED'::character varying,created_by uuid,created_at timestamptz default now());
create table public.staff_weekly_offs(id int8 generated by default as identity primary key,staff_id int4,day_of_week int2,effective_from date default CURRENT_DATE,effective_to date);
create table public.summary_staff_payouts(id int4 generated by default as identity primary key,summary_id varchar,staff_name varchar,payout_type varchar,amount numeric,mode varchar default 'Cash'::character varying,staff_id int4);
create table public.users(id uuid default gen_random_uuid() primary key,name varchar,pin_hash varchar,role varchar,outlet_id int4,can_switch_outlet bool default false,active bool default true,permissions jsonb default '{"stock": true, "salary": false, "summary": true, "purchase": true, "attendance": true}'::jsonb,created_at timestamptz default now(),auth_user_id uuid,pin_set_at timestamptz,last_login_at timestamptz,failed_login_attempts int4 default 0,locked_until timestamptz,staff_id int4,pin_setup_hash text,pin_setup_expires_at timestamptz,deactivated_at timestamptz,access_class text default 'STAFF'::text,is_super_user bool default false);

alter table salary_records add unique(outlet_id,staff_id,period_start);
alter table staff_advance_deductions add primary key(advance_id,period_start);
create table summary_expenses(summary_id varchar,category varchar,amount numeric,mode varchar);
create table summary_vendor_payouts(summary_id varchar,vendor_name varchar,amount numeric,mode varchar);
create table business_days(outlet_id integer,business_date date,summary_status text,unique(outlet_id,business_date));
create table salary_payroll_audit(id bigint generated by default as identity,salary_record_id varchar,actor_user_id uuid,action text,prior_status text,new_status text,payroll_details jsonb,created_at timestamptz default now());
create table staff_status_history(id bigint generated by default as identity,staff_id integer,status text,effective_from date,note text,changed_by uuid);
create function private.actor_id() returns uuid language sql stable security definer set search_path='' as $$select id from public.users where auth_user_id=auth.uid() and active limit 1$$;
create function private.actor_outlet() returns integer language sql stable security definer set search_path='' as $$select outlet_id from public.users where auth_user_id=auth.uid() and active limit 1$$;
create function private.actor_staff_id() returns integer language sql stable security definer set search_path='' as $$select staff_id from public.users where auth_user_id=auth.uid() and active limit 1$$;
create function private.is_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.users where auth_user_id=auth.uid() and active and access_class='ADMIN')$$;
create function private.is_manager() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.users where auth_user_id=auth.uid() and active and role in('Manager','Ops Manager'))$$;
create function private.can_operate_outlet(integer) returns boolean language sql stable security definer set search_path='' as $$select private.is_admin() or $1=private.actor_outlet()$$;
create function public.get_effective_business_day(integer,timestamptz) returns date language sql stable as $$select ($2 at time zone 'Asia/Kolkata')::date$$;
create function public.get_outlet_hours(integer,date) returns table(close_time time,is_closed boolean) language sql stable as $$select '22:00'::time,false$$;

CREATE OR REPLACE FUNCTION private.has_module_access(p_module text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select coalesce((select case
    when u.access_class='ADMIN' then true
    when p_module not in('orders','purchase','extra-time','delta','summary') then false
    when jsonb_typeof(u.permissions->'module_access'->p_module)='boolean'
      then (u.permissions->'module_access'->>p_module)::boolean
    else p_module in('orders','purchase','extra-time')
      or (p_module='summary' and u.role in('Manager','Ops Manager'))
    end from public.users u where u.auth_user_id=auth.uid() and u.active limit 1),false)
$function$
;
CREATE OR REPLACE FUNCTION private.require_module_access(p_module text)
 RETURNS void
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
begin
  if not private.has_module_access(p_module) then raise exception 'Access to this module is disabled' using errcode='42501';end if;
end $function$
;
CREATE OR REPLACE FUNCTION private.can_use_summary(p_outlet integer)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select private.has_module_access('summary') and private.can_operate_outlet(p_outlet)
$function$
;
CREATE OR REPLACE FUNCTION private.validate_module_permissions(p_permissions jsonb)
 RETURNS void
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO ''
AS $function$
begin
  if p_permissions is null then return;end if;
  if jsonb_typeof(p_permissions)<>'object' then raise exception 'Permissions must be an object';end if;
  if p_permissions ? 'module_access' then
    if jsonb_typeof(p_permissions->'module_access')<>'object' then raise exception 'Module access must be an object';end if;
    if exists(select 1 from jsonb_each(p_permissions->'module_access') e
      where e.key not in('orders','purchase','extra-time','delta','summary') or jsonb_typeof(e.value)<>'boolean') then
      raise exception 'Choose true or false for the five supported access domains';
    end if;
  end if;
end $function$
;
CREATE OR REPLACE FUNCTION public.get_salary_estimate(p_staff_id integer, p_start date, p_end date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_actor public.users;v_target public.staff;
begin
 select * into v_actor from public.users where auth_user_id=auth.uid() and active=true;
 if not found then raise exception 'Authenticated CafeTracker user required';end if;
 select * into v_target from public.staff where id=p_staff_id;if not found then raise exception 'Staff not found';end if;
 if coalesce(v_actor.access_class,'STAFF')<>'ADMIN' and coalesce(v_actor.staff_id,0)<>p_staff_id then raise exception 'You can only view your own salary';end if;
 return public.get_salary_estimate_internal(p_staff_id,p_start,p_end);
end $function$
;
CREATE OR REPLACE FUNCTION public.owner_update_staff(p_staff_id integer, p_name text, p_outlet_id integer, p_role text, p_basic_salary numeric, p_joining_date date, p_active boolean, p_permissions jsonb, p_notes text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$ declare actor uuid; uid uuid; begin
 perform private.validate_module_permissions(p_permissions);
 if p_role is null or p_role not in('Staff','Manager','Ops Manager') then raise exception 'Choose a valid staff role';end if; actor:=auth.uid(); if actor is null or not exists(select 1 from public.users u where u.auth_user_id=actor and u.role='Owner' and u.active=true) then raise exception 'Owner access required.'; end if; if nullif(trim(p_name),'') is null or p_basic_salary is null or p_basic_salary<=0 or p_joining_date is null then raise exception 'Name, salary and joining date are required.'; end if; select u.id into uid from public.users u where u.staff_id=p_staff_id; if uid is null then raise exception 'User profile not found.'; end if; update public.staff set name=trim(p_name),outlet_id=p_outlet_id,basic_salary=p_basic_salary,joining_date=p_joining_date,active=p_active,notes=nullif(trim(coalesce(p_notes,'')),'') where id=p_staff_id; update public.users set name=trim(p_name),outlet_id=p_outlet_id,role=coalesce(nullif(trim(p_role),''),'Staff'),active=p_active,permissions=coalesce(p_permissions,'{}'::jsonb),deactivated_at=case when p_active then null else coalesce(deactivated_at,now()) end where id=uid; return jsonb_build_object('staff_id',p_staff_id,'user_id',uid,'active',p_active); end $function$
;
CREATE OR REPLACE FUNCTION public.owner_set_staff_status(p_staff_id integer, p_status text, p_effective_from date DEFAULT CURRENT_DATE, p_note text DEFAULT NULL::text)
 RETURNS staff
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_actor public.users;v_staff public.staff;v_status text:=upper(trim(p_status));v_date date:=coalesce(p_effective_from,current_date);
begin
 select * into v_actor from public.users where auth_user_id=auth.uid() and active=true;if not found or coalesce(v_actor.access_class,'STAFF')<>'ADMIN' then raise exception 'Admin access required';end if;
 if v_status not in('ACTIVE','VACATION','LEAVE','INACTIVE','LEFT') then raise exception 'Invalid staff status';end if;
 update public.staff set employment_status=v_status,status_effective_from=v_date,status_note=nullif(trim(coalesce(p_note,'')),''),active=(v_status not in('INACTIVE','LEFT')),employment_end_date=case when v_status='LEFT' then v_date when v_status='ACTIVE' then null else employment_end_date end where id=p_staff_id returning * into v_staff;if not found then raise exception 'Staff not found';end if;
 insert into public.staff_status_history(staff_id,status,effective_from,note,changed_by) values(p_staff_id,v_status,v_date,nullif(trim(coalesce(p_note,'')),''),v_actor.id);
 update public.users set active=(v_status not in('INACTIVE','LEFT')),deactivated_at=case when v_status in('INACTIVE','LEFT') then now() else null end where staff_id=p_staff_id;return v_staff;
end $function$
;

alter table staff_advance_requests enable row level security;alter table staff_advance_deductions enable row level security;grant select on all tables in schema public to authenticated;grant execute on all functions in schema private to authenticated;
create policy advance_requests_visible on staff_advance_requests for select to authenticated using(private.is_admin() or staff_id=private.actor_staff_id() or (private.is_manager() and outlet_id=private.actor_outlet()));
create policy advance_summary_reconciliation on staff_advance_requests for select to authenticated using(status in('APPROVED','PAID') and private.can_use_summary(outlet_id));
create policy advance_deductions_visible on staff_advance_deductions for select to authenticated using(exists(select 1 from staff_advance_requests a where a.id=advance_id));
create function public.finalize_salary_record_v2(integer,date,date,date,uuid) returns void language sql as $$select$$;
