import { jsPDF } from 'jspdf';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>'₹'+Math.round(Math.abs(Number(value)||0)).toLocaleString('en-IN');
const signed=value=>Number(value)===0?'₹0':(Number(value)<0?'−':'+')+money(value);
const rowAmount=([,amount,kind])=>kind==='balance'?money(amount):signed(amount);

function summaryCanvas({staff,periodStart,periodEnd,payDate,status,rows,net}) {
  const width=1200,pad=72,usable=width-pad*2;
  const measure=document.createElement('canvas').getContext('2d');
  measure.font='30px Arial, sans-serif';
  const wrap=(label,maxWidth)=>{
    const lines=[''];
    for(const word of String(label).split(/\s+/)){
      const last=lines.length-1,next=lines[last]?(lines[last]+' '+word):word;
      if(measure.measureText(next).width>maxWidth&&lines[last])lines.push(word);
      else lines[last]=next;
    }
    return lines;
  };
  const rowData=rows.map(([label,amount,kind])=>({lines:wrap(label,usable-340),amount:Number(amount)||0,kind}));
  const rowHeight=row=>Math.max(70,row.lines.length*38+28);
  const rowsHeight=rowData.reduce((sum,row)=>sum+rowHeight(row),0);
  const height=480+rowsHeight+220;
  const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;
  const ctx=canvas.getContext('2d');
  if(!ctx)throw new Error('Image export is unavailable on this device.');
  ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);
  ctx.fillStyle='#202024';ctx.font='bold 54px Arial, sans-serif';ctx.fillText('Salary summary',pad,110);
  ctx.font='29px Arial, sans-serif';
  [['Staff',staff],['Pay period',periodStart+' to '+periodEnd],['Pay date',payDate],['Status',status]].forEach(([label,value],i)=>{
    ctx.fillStyle='#555';ctx.fillText(label+':',pad,175+i*50);
    ctx.fillStyle='#202024';ctx.fillText(String(value),pad+190,175+i*50);
  });
  ctx.fillStyle='#cb202d';ctx.fillRect(pad,385,usable,5);
  let y=435;
  ctx.strokeStyle='#e5e5e5';ctx.lineWidth=2;
  for(const row of rowData){
    const h=rowHeight(row);
    ctx.fillStyle='#242424';ctx.font='30px Arial, sans-serif';
    row.lines.forEach((line,i)=>ctx.fillText(line,pad+18,y+43+i*38));
    ctx.font='bold 31px Arial, sans-serif';ctx.textAlign='right';
    ctx.fillText(row.kind==='balance'?money(row.amount):signed(row.amount),width-pad-18,y+43);
    ctx.textAlign='left';
    ctx.beginPath();ctx.moveTo(pad+15,y+h);ctx.lineTo(width-pad-15,y+h);ctx.stroke();
    y+=h;
  }
  y+=35;
  ctx.fillStyle='#cb202d';ctx.fillRect(pad,y,usable,106);
  ctx.fillStyle='#fff';ctx.font='bold 38px Arial, sans-serif';ctx.fillText('Net salary',pad+28,y+68);
  ctx.textAlign='right';ctx.fillText(money(net),width-pad-28,y+68);ctx.textAlign='left';
  ctx.fillStyle='#777';ctx.font='23px Arial, sans-serif';ctx.fillText('Generated by ChaiTracker',pad,y+158);
  return canvas;
}

function blobFromDataUrl(url,type) {
  const binary=atob(url.split(',')[1]),bytes=new Uint8Array(binary.length);
  for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);
  return new Blob([bytes],{type});
}

function pdfFromCanvas(canvas) {
  const pdf=new jsPDF({unit:'pt',format:'a4',compress:true});
  const pageWidth=pdf.internal.pageSize.getWidth(),pageHeight=pdf.internal.pageSize.getHeight(),margin=35;
  const imageWidth=pageWidth-margin*2,scale=imageWidth/canvas.width;
  const sourcePageHeight=Math.floor((pageHeight-margin*2)/scale);
  for(let sourceY=0,page=0;sourceY<canvas.height;sourceY+=sourcePageHeight,page++){
    if(page)pdf.addPage();
    const sliceHeight=Math.min(sourcePageHeight,canvas.height-sourceY);
    const slice=document.createElement('canvas');slice.width=canvas.width;slice.height=sliceHeight;
    slice.getContext('2d').drawImage(canvas,0,sourceY,canvas.width,sliceHeight,0,0,canvas.width,sliceHeight);
    pdf.addImage(slice.toDataURL('image/jpeg',.94),'JPEG',margin,margin,imageWidth,sliceHeight*scale);
  }
  return pdf.output('blob');
}

function download(blob,name) {
  const url=URL.createObjectURL(blob),anchor=document.createElement('a');
  anchor.href=url;anchor.download=name;document.body.append(anchor);anchor.click();anchor.remove();
  setTimeout(()=>URL.revokeObjectURL(url),60000);
}

async function offerFile(blob,name,title,previewFallback=false) {
  const file=new File([blob],name,{type:blob.type});
  if(navigator.share&&navigator.canShare?.({files:[file]})){
    try{await navigator.share({files:[file],title});return;}
    catch(error){if(error.name==='AbortError')return;}
  }
  if(previewFallback){
    const url=URL.createObjectURL(blob),opened=window.open(url,'_blank');
    if(opened){setTimeout(()=>URL.revokeObjectURL(url),60000);return;}
    URL.revokeObjectURL(url);
  }
  download(blob,name);
}

export function showPayrollSummary({staff,periodStart,periodEnd,payDate,status,rows,net}) {
  document.querySelector('.payroll-summary-overlay')?.remove();
  const previousOverflow=document.body.style.overflow;
  const overlay=document.createElement('div');overlay.className='payroll-summary-overlay';
  const label=staff+' · '+periodStart+' to '+periodEnd;
  const fileBase='salary-'+staff.trim().replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()+'-'+periodStart;
  const nonzero=rows.filter(([,amount,kind])=>kind==='balance'||Number(amount)!==0);
  const message=['*Salary summary*','Staff: '+staff,'Period: '+periodStart+' to '+periodEnd,'Pay date: '+payDate,'Status: '+status,'',...nonzero.map(row=>row[0]+': '+rowAmount(row)),'','*Net salary: '+money(net)+'*'].join('\n');
  overlay.innerHTML=`<div class="payroll-summary-toolbar"><button type="button" data-summary-back>‹ Back to payroll</button><strong>Salary summary</strong></div>
    <div class="payroll-summary-content">
      <article class="payroll-summary-paper"><header><h1>Salary summary</h1><p><strong>Staff:</strong> ${escapeHtml(staff)}</p><p><strong>Pay period:</strong> ${escapeHtml(periodStart)} to ${escapeHtml(periodEnd)}</p><p><strong>Pay date:</strong> ${escapeHtml(payDate)}</p><p><strong>Status:</strong> ${escapeHtml(status)}</p></header>
        <div class="payroll-summary-rows">${rows.map(row=>`<div class="payroll-summary-row"><span>${escapeHtml(row[0])}</span><strong>${rowAmount(row)}</strong></div>`).join('')}</div>
        <div class="payroll-summary-net"><span>Net salary</span><strong>${money(net)}</strong></div>
        <p class="payroll-summary-footnote">Generated by ChaiTracker · ${escapeHtml(new Date().toLocaleString('en-IN'))}</p></article>
      <div class="payroll-summary-actions"><button type="button" data-summary-whatsapp>WhatsApp message</button><button type="button" data-summary-jpeg>Save JPEG</button><button type="button" data-summary-pdf>Save PDF</button><button type="button" data-summary-print>Print</button></div>
      <div class="payroll-summary-message" hidden><label for="payrollWhatsAppText">WhatsApp message</label><textarea id="payrollWhatsAppText" rows="12"></textarea><div><button type="button" data-summary-copy>Copy message</button><button type="button" data-summary-open-whatsapp>Open WhatsApp</button></div></div>
      <p class="payroll-summary-feedback" role="status" aria-live="polite"></p>
    </div>`;
  document.body.append(overlay);document.body.style.overflow='hidden';document.body.classList.add('payroll-summary-open');
  const feedback=overlay.querySelector('.payroll-summary-feedback');
  const say=text=>{feedback.textContent=text;};
  const close=()=>{overlay.remove();document.body.style.overflow=previousOverflow;document.body.classList.remove('payroll-summary-open');};
  overlay.querySelector('[data-summary-back]').onclick=close;
  overlay.querySelector('[data-summary-whatsapp]').onclick=()=>{
    const box=overlay.querySelector('.payroll-summary-message');box.hidden=!box.hidden;
    if(!box.hidden){box.querySelector('textarea').value=message;box.scrollIntoView({behavior:'smooth',block:'nearest'});}
  };
  overlay.querySelector('[data-summary-copy]').onclick=async()=>{
    const input=overlay.querySelector('#payrollWhatsAppText');
    try{await navigator.clipboard.writeText(input.value);say('Message copied.');}
    catch{input.select();document.execCommand('copy');say('Message selected for copying.');}
  };
  overlay.querySelector('[data-summary-open-whatsapp]').onclick=()=>{
    const url='https://wa.me/?text='+encodeURIComponent(overlay.querySelector('#payrollWhatsAppText').value);
    const opened=window.open(url,'_blank');
    if(opened)opened.opener=null;
    else say('Allow pop-ups to open WhatsApp, or copy the message above.');
  };
  const makeCanvas=()=>summaryCanvas({staff,periodStart,periodEnd,payDate,status,rows,net});
  overlay.querySelector('[data-summary-jpeg]').onclick=async()=>{
    try{const blob=blobFromDataUrl(makeCanvas().toDataURL('image/jpeg',.94),'image/jpeg');await offerFile(blob,fileBase+'.jpg',label);}
    catch(error){say(error.message||'Could not create the JPEG.');}
  };
  const makePdf=()=>pdfFromCanvas(makeCanvas());
  overlay.querySelector('[data-summary-pdf]').onclick=async()=>{
    try{await offerFile(makePdf(),fileBase+'.pdf',label);}
    catch(error){say(error.message||'Could not create the PDF.');}
  };
  overlay.querySelector('[data-summary-print]').onclick=async()=>{
    try{
      if(/iPad|iPhone|iPod/.test(navigator.userAgent)||window.matchMedia('(display-mode: standalone)').matches){
        await offerFile(makePdf(),fileBase+'.pdf',label,true);
        say('Choose Print in the PDF share sheet or viewer.');
      }else window.print();
    }catch(error){say(error.message||'Could not open print options. Try Save PDF.');}
  };
}
