import {shiftMonth,monthEnd} from './businessMetrics.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v===null||v===undefined?'—':'₹'+Number(v).toLocaleString('en-IN',{maximumFractionDigits:2});
const labels={PAY_VENDOR:'Paid vendor',RECEIVE_VENDOR:'Received from vendor',ADD_PAYABLE:'Added amount to pay',ADD_RECEIVABLE:'Added amount to receive'};
export function creditTotals(accounts){const known=accounts.filter(a=>a.balance!==null&&a.balance!==undefined);return {toPay:known.length?known.reduce((s,a)=>s+Math.max(0,Number(a.balance)),0):null,toReceive:known.length?known.reduce((s,a)=>s+Math.max(0,-Number(a.balance)),0):null,unknown:accounts.length-known.length,known:known.length};}
export async function renderVendorCredits(view,client,profile){
 if(profile.access_class!=='ADMIN'){view.innerHTML='<h2>Admin access required</h2>';return;}
 const token={};view._creditsRequest=token;const outlet=profile.context_outlet_id?Number(profile.context_outlet_id):null;
 const requestedMonth=profile._creditsMonth?profile._creditsMonth+'-01':null;
 const {data,error}=await client.rpc('get_vendor_credits',{p_outlet_id:outlet,p_month:requestedMonth});
 if(view._creditsRequest!==token)return;
 if(error||!data){view.innerHTML=`<h2>Credits unavailable</h2><p class="form-error">${esc(error?.message||'Please try again.')}</p><button id="creditRetry" class="secondary" type="button">Retry</button>`;view.querySelector('#creditRetry').onclick=()=>renderVendorCredits(view,client,profile);return;}
 let tab='all',search='',closingData=null,closingMonth=shiftMonth(data.business_day.slice(0,7),-1),selectedMovement=null;
 const currentMonth=data.business_day.slice(0,7),selectedMonth=data.month.slice(0,7),totals=creditTotals(data.accounts);
 const lastClosed=data.month_states.filter(s=>s.status==='CLOSED').sort((a,b)=>a.period_month.localeCompare(b.period_month)).at(-1)?.period_month;
 const message=profile._creditsNotice||'';delete profile._creditsNotice;
 const option=(value,label)=>`<option value="${esc(value)}">${esc(label)}</option>`;
 const refresh=()=>renderVendorCredits(view,client,profile);
 async function save(form,action,payload,revision=data.revision){
  const target=form.querySelector('[role="status"]'),button=form.querySelector('button[type="submit"]');
  if(!form.reportValidity())return;
  const base={...payload,outlet_id:outlet,expected_revision:revision};const signature=JSON.stringify({action,base});
  if(form._requestSignature!==signature){form._requestSignature=signature;form._requestId=crypto.randomUUID();}
  button.disabled=true;target.textContent='Saving…';
  try{const r=await client.rpc('manage_vendor_credits',{p_action:action,p_payload:{...base,request_id:form._requestId}});if(r.error)throw r.error;if(view._creditsRequest!==token)return;profile._creditsNotice=action==='CLOSE'?'Monthly balances confirmed and carried forward.':action==='REOPEN'?'Month reopened. Confirm balances again after corrections.':action==='VOID'?'Movement voided; its audit history is retained.':'Balance movement recorded.';await refresh();}
  catch(e){if(view._creditsRequest!==token)return;target.textContent=e.message||'Unable to save. Retry with the same details.';button.disabled=false;}
 }
 const renderRows=()=>{
  const rows=data.accounts.filter(a=>(!search||(a.vendor_name+' '+a.outlet_name).toLowerCase().includes(search))&&(tab==='all'||a.balance!==null&&(tab==='pay'?Number(a.balance)>0:Number(a.balance)<0)));
  view.querySelector('#creditVendorRows').innerHTML=rows.length?rows.map(a=>`<tr><th scope="row">${esc(a.vendor_name)}${!outlet?`<small><button type="button" data-credit-cafe="${a.outlet_id}">${esc(a.outlet_name)} ›</button></small>`:''}</th><td>${a.balance===null?'—':money(Math.max(0,Number(a.balance)))}</td><td>${a.balance===null?'—':money(Math.max(0,-Number(a.balance)))}</td><td>${a.confirmed_month?`<span class="credit-confirmed">Confirmed ${esc(a.confirmed_month.slice(0,7))}</span><small>${Number(a.movements)!==0?'Includes later movements':'Balance carried forward'}</small>`:'<span class="credit-unconfirmed">Not confirmed</span>'}</td></tr>`).join(''):'<tr><td colspan="4">No vendors match this view.</td></tr>';
  view.querySelectorAll('[data-credit-cafe]').forEach(b=>b.onclick=()=>view.dispatchEvent(new CustomEvent('app:navigate',{bubbles:true,detail:{module:'credits',outletId:Number(b.dataset.creditCafe)}})));
 };
 const renderClosing=()=>{
  const area=view.querySelector('#creditClosingPanel');if(!closingData){area.innerHTML='';return;}
  const state=closingData.month_states.find(s=>s.outlet_id===outlet&&s.period_month===closingMonth+'-01');
  area.innerHTML=`<section class="biz-section credit-closing"><div class="biz-section-heading"><div><h3>Monthly closing</h3><p>Confirm every vendor against their statement. Positive balances are to pay; vendor credits are to receive.</p></div><button id="creditClosePanel" class="ghost" type="button">Cancel</button></div><label class="credit-month-label">Closing month<input id="creditClosingMonth" type="month" max="${shiftMonth(currentMonth,-1)}" value="${closingMonth}" required></label>
   ${state?.status==='CLOSED'?`<p class="notice">${esc(closingMonth)} is closed. Its balances are carried forward.</p><form id="creditReopenForm" class="credit-simple-form"><label>Reason to reopen<input name="note" minlength="3" maxlength="500" required placeholder="Reason for correction"></label><button class="secondary" type="submit">Reopen month</button><p class="form-error" role="status"></p></form>`:
   `<form id="creditClosingForm"><div class="biz-table-wrap"><table class="biz-table credit-closing-table"><thead><tr><th>Vendor</th><th>Direction</th><th>Confirmed amount</th></tr></thead><tbody>${closingData.accounts.map(a=>`<tr><th scope="row">${esc(a.vendor_name)}</th><td><select name="side_${a.vendor_id}" aria-label="Balance direction for ${esc(a.vendor_name)}">${option('pay','To pay')}${option('receive','To receive')}</select></td><td><input name="amount_${a.vendor_id}" aria-label="Confirmed balance for ${esc(a.vendor_name)}" type="number" min="0" max="999999999999.99" step="0.01" required value="${a.balance===null?'':Math.abs(Number(a.balance))}" placeholder="Enter amount"></td></tr>`).join('')}</tbody></table></div><p class="biz-small-note">Use zero for settled vendors. Suggested amounts are carried balances; verify them before closing.</p><label>Statement reference / closing note<input name="note" minlength="3" maxlength="500" required placeholder="e.g. September supplier statements reconciled"></label><label class="credit-confirm-check"><input name="confirmed" type="checkbox" required>I have confirmed every vendor balance.</label><button class="primary" type="submit">Close ${esc(closingMonth)} & carry balances</button><p class="form-error" role="status"></p></form>`}</section>`;
  area.querySelector('#creditClosePanel').onclick=()=>{closingData=null;renderClosing();};
  area.querySelector('#creditClosingMonth').onchange=e=>{if(e.target.value&&e.target.value<currentMonth)loadClosing(e.target.value);};
  const form=area.querySelector('#creditClosingForm');if(form){for(const a of closingData.accounts)form.elements.namedItem('side_'+a.vendor_id).value=Number(a.balance)<0?'receive':'pay';form.onsubmit=e=>{e.preventDefault();const balances=closingData.accounts.map(a=>({vendor_id:a.vendor_id,balance:Number(form.elements.namedItem('amount_'+a.vendor_id).value)*(form.elements.namedItem('side_'+a.vendor_id).value==='receive'?-1:1)}));save(form,'CLOSE',{month:closingMonth+'-01',balances,note:form.elements.note.value},closingData.revision);};}
  const reopen=area.querySelector('#creditReopenForm');if(reopen)reopen.onsubmit=e=>{e.preventDefault();save(reopen,'REOPEN',{month:closingMonth+'-01',note:reopen.elements.note.value},closingData.revision);};
 };
 async function loadClosing(month=closingMonth){
  const request={};view._creditsClosingRequest=request;closingMonth=month;const area=view.querySelector('#creditClosingPanel');area.innerHTML='<p class="section-help">Loading monthly balances…</p>';
  const r=await client.rpc('get_vendor_credits',{p_outlet_id:outlet,p_month:month+'-01'});if(view._creditsRequest!==token||view._creditsClosingRequest!==request)return;
  if(r.error){area.innerHTML=`<p class="form-error">${esc(r.error.message)}</p>`;return;}closingData=r.data;renderClosing();area.scrollIntoView?.({block:'start',behavior:'smooth'});
 }
 view.innerHTML=`<div class="business-dashboard vendor-credits"><header class="biz-heading"><div><span class="eyebrow">${esc(outlet?data.outlets[0]?.name:'All cafés')} · Supplier balances</span><h2>Credits</h2><p>To pay, to receive and monthly reconciliation</p></div><div class="biz-date-controls"><label>Reporting month<input id="creditReportingMonth" type="month" value="${selectedMonth}" max="${currentMonth}"></label><button id="creditRefresh" class="ghost" type="button">Refresh</button></div></header>
  ${message?`<p class="notice" role="status">${esc(message)}</p>`:''}
  <section class="biz-kpi-grid credit-kpis"><article class="biz-kpi hero"><span>To pay</span><strong>${money(totals.toPay)}</strong><small>Outstanding amounts owed to vendors</small></article><article class="biz-kpi profit"><span>To receive</span><strong>${money(totals.toReceive)}</strong><small>Refunds and balances owed by vendors</small></article><article class="biz-kpi"><span>Not confirmed</span><strong>${totals.unknown}</strong><small>Vendor/café balances need confirmation</small></article></section>
  <p class="biz-method-inline">Balances come from your monthly confirmation plus recorded movements. Purchases and Daily Summary payments are not automatically deducted here. Movements in Credits do not create sales or expenses.</p>
  ${totals.unknown?'<p class="notice">Unconfirmed balances are excluded from totals. Complete an initial monthly closing to establish them.</p>':''}
  ${!outlet?'<p class="notice">Select a café above to record movements or close a month.</p>':`<div class="credit-toolbar"><button id="creditOpenMovement" class="secondary" type="button">Record movement</button><button id="creditOpenClosing" class="primary" type="button">Monthly closing</button><span class="biz-small-note">${lastClosed?'Latest closed month: '+esc(lastClosed.slice(0,7)):'No month closed yet'}</span></div>`}
  <div id="creditClosingPanel"></div>
  <section id="creditMovementPanel" class="biz-section" hidden><h3>Record balance movement</h3><p class="biz-small-note">Use this for a vendor payment, receipt or balance adjustment. Record cash payments in Daily Summary as well.</p><form id="creditMovementForm" class="credit-movement-form"><label>Vendor<select name="vendor_id" required>${option('','Select vendor')}${data.vendors.map(v=>option(v.id,v.name)).join('')}</select></label><label>Type<select name="kind">${Object.entries(labels).map(([k,v])=>option(k,v)).join('')}</select></label><label>Business date<input name="business_date" type="date" max="${data.business_day}" value="${data.business_day}" required></label><label>Amount<input name="amount" type="number" min="0.01" max="999999999999.99" step="0.01" required></label><label class="credit-note-field">Reference / note<input name="note" minlength="3" maxlength="500" required placeholder="Payment reference or reason"></label><div class="credit-form-buttons"><button class="primary" type="submit">Save movement</button><button id="creditCancelMovement" class="ghost" type="button">Cancel</button></div><p class="form-error" role="status"></p></form></section>
  <section class="biz-section"><div class="biz-section-heading"><div><h3>All vendors</h3><p>${esc(selectedMonth)} · vendor balances are shown separately</p></div><label class="credit-search">Search<input id="creditVendorSearch" type="search" placeholder="Vendor or café"></label></div><div class="credit-tabs" role="tablist" aria-label="Vendor balance views"><button type="button" data-credit-tab="all" role="tab" aria-selected="true">All vendors</button><button type="button" data-credit-tab="pay" role="tab" aria-selected="false">To pay</button><button type="button" data-credit-tab="receive" role="tab" aria-selected="false">To receive</button></div><div class="biz-table-wrap"><table class="biz-table"><thead><tr><th>Vendor</th><th>To pay</th><th>To receive</th><th>Confirmation</th></tr></thead><tbody id="creditVendorRows"></tbody></table></div></section>
  <section class="biz-section"><div class="biz-section-heading"><div><h3>Movements · ${esc(selectedMonth)}</h3><p>Payments, receipts and adjustments · corrections retain history</p></div></div><div class="biz-table-wrap"><table class="biz-table"><thead><tr><th>Date / vendor</th><th>Type</th><th>Amount</th><th>Reference</th><th></th></tr></thead><tbody>${data.movements.length?data.movements.map(m=>`<tr class="${m.voided_at?'credit-voided':''}"><th>${esc(m.business_date)}<small>${esc(m.vendor_name)}${!outlet?' · '+esc(m.outlet_name):''}</small></th><td>${esc(labels[m.kind]||m.kind)}${m.voided_at?'<small>Voided</small>':''}</td><td>${money(m.amount)}</td><td>${esc(m.note)}${m.void_reason?`<small>${esc(m.void_reason)}</small>`:''}</td><td>${outlet&&!m.voided_at&&(!lastClosed||m.business_date>monthEnd(lastClosed.slice(0,7)))?`<button type="button" class="ghost" data-credit-void="${esc(m.id)}">Correct</button>`:''}</td></tr>`).join(''):'<tr><td colspan="5">No movements recorded this month.</td></tr>'}</tbody></table></div><form id="creditVoidForm" class="credit-simple-form" hidden><label>Reason for correction<input name="note" minlength="3" maxlength="500" required placeholder="Explain why this movement should be voided"></label><button class="secondary" type="submit">Void movement</button><button id="creditCancelVoid" class="ghost" type="button">Cancel</button><p class="form-error" role="status"></p></form></section>
  <details class="biz-methodology"><summary>How monthly closing works</summary><p>Confirm every vendor’s month-end balance once a month. Positive balances are to pay, negative balances are to receive and zero means settled. These are supplier balances; receipts are not café sales.</p><p>A closing replaces the previous carried balance with the confirmed statement balance. Later movements are added to it. Closed periods reject backdated movements or corrections. Reopen the latest closed month with a reason, then close it again after correcting. Every closing, reopen and movement is audited.</p><p>Unknown balances are unavailable, rather than assumed zero. Totals never offset amounts to pay against amounts to receive across vendors or cafés.</p></details></div>`;
 renderRows();
 view.querySelector('#creditRefresh').onclick=refresh;
 view.querySelector('#creditReportingMonth').onchange=e=>{if(e.target.value&&e.target.value<=currentMonth){profile._creditsMonth=e.target.value;refresh();}};
 view.querySelector('#creditVendorSearch').oninput=e=>{search=e.target.value.trim().toLowerCase();renderRows();};
 view.querySelectorAll('[data-credit-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.creditTab;view.querySelectorAll('[data-credit-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));renderRows();});
 view.querySelector('#creditOpenClosing')?.addEventListener('click',()=>loadClosing());
 view.querySelector('#creditOpenMovement')?.addEventListener('click',()=>{view.querySelector('#creditMovementPanel').hidden=false;view.querySelector('#creditMovementPanel').scrollIntoView?.({block:'start',behavior:'smooth'});});
 view.querySelector('#creditCancelMovement').onclick=()=>{view.querySelector('#creditMovementPanel').hidden=true;};
 const mf=view.querySelector('#creditMovementForm');mf.onsubmit=e=>{e.preventDefault();save(mf,'MOVEMENT',{vendor_id:Number(mf.elements.vendor_id.value),business_date:mf.elements.business_date.value,kind:mf.elements.kind.value,amount:Number(mf.elements.amount.value),note:mf.elements.note.value});};
 const vf=view.querySelector('#creditVoidForm');view.querySelectorAll('[data-credit-void]').forEach(b=>b.onclick=()=>{selectedMovement=b.dataset.creditVoid;vf.hidden=false;vf.elements.note.focus();});view.querySelector('#creditCancelVoid').onclick=()=>{vf.hidden=true;};vf.onsubmit=e=>{e.preventDefault();if(selectedMovement)save(vf,'VOID',{movement_id:selectedMovement,note:vf.elements.note.value});};
}
